version: "3.7"

services:
  node:
    container_name: 'pricing-events-node'
    build:
      context: .
      dockerfile: Docker/Dockerfile
    volumes:
      - .:/app
    ports:
      - 5000:5000
      - 3001:3001