name: Jira CI
on: 
  push:
    branches:
      - main
      - production
      - master
      - feature/github-actions-config2
jobs:
  transition-issue:
      name: Branch Issue
      runs-on: ubuntu-latest
      steps:
      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${{github.event.push}} | awk -F/ '{print $NF}')"
        shell: bash
        id: get_branch_name
      - name: teste
        run: echo ${{ steps.get_branch_name.outputs.branch }}
  log-github-event-goodies:
    name: "LOG Everything on GitHub Event"
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          echo "${{toJSON(github)}}"      

      # - when: on_success
      # - name: Login
      #   uses: atlassian/gajira-login@master
      #   env:
      #     JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      #     JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      #     JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      #     branch_name: ${{github.event.pull_request.head.ref}} 
      # - name: Comment on issue
      #   uses: atlassian/gajira-comment@master
      #   with:
      #     issue: ${{ steps.extract_branch.outputs.branch }}
      #     comment: ${{secrets.JIRA_COMMENT_DONE}}
      # - name: Transition issue
      #   uses: atlassian/gajira-transition@master
      #   with:
      #     issue: ${{ steps.extract_branch.outputs.branch }}
      #     transition: ${{secrets.JIRA_STEP_DONE}}